service: aws-polling-task-scheduler

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    TASK_TABLE: ${self:service}-${opt:stage, self:provider.stage}-tasks
    ID_INDEX:   ${self:service}-${opt:stage, self:provider.stage}-tasks-by-id
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TASK_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TASK_TABLE}/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${self:provider.region}:*:task-*"

functions:
  poll-scheduled:
    cljs: aws-polling-task-scheduler.handlers/poll-scheduled
    events:
      - schedule: rate(5 minutes)
  schedule:
    cljs: aws-polling-task-scheduler.handlers/schedule
    events:
      - http:
          path:   task/schedule
          method: post
          cors:   true
  unschedule:
    cljs: aws-polling-task-scheduler.handlers/unschedule
    events:
      - http:
          path:   task/{id}
          method: delete

plugins:
  - serverless-cljs-plugin

resources:
  Resources:
    TaskTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.TASK_TABLE}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType:       HASH
          - AttributeName: timestamp
            KeyType:       RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.ID_INDEX}
            KeySchema:
              - AttributeName: id
                KeyType:       HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
